src/mimar/hemidi/urls.py
from django.conf.urls import url

#from .views import  all_post,un_post
from .views import  un_post , pag_post
from . import   views
from .views import  HomePageView
app_name = 'hemidi'

"""urlpatterns = [
    url(r'^/$', views.all_post , name = 'all_post'),
    url(r'^/(?P<id>\d+)$', views.un_post , name='un_post'),
    url(r'^/form', views.form_p , name='un_post_form'),
    url('/hemidi', HomePageView.as_view(), name='home'),



]"""
urlpatterns = [

    url(r'^/(?P<id>\d+)$', un_post , name='un_post'),
    url(r'form', pag_post , name='un_post_form'),
    url(r'^/$', views.all_post, name='home'),
    url(r'^/login/$',  views.get_name, name='login'),
    url(r'^/signup/$', views.signup, name='signup'),


]

src/mimar/mimar/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import  settings
from django.conf.urls.static import  static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', include('hemidi.urls' , namespace='home')) ,
    path('home_page', include('accounts.urls' , namespace='home')) ,



]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

src/mimar/hemidi/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
#https://stackoverflow.com/questions/31130706/dropdown-in-django-model /// dropdown django
COLOR_CHOICES = (
    ('RC','RC'),
    ('R', 'R'),
    ('RC','RC'),
    ('R2','C3'),
    ('black','BLACK'),
)
class info_tp(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    nome_prof = models.CharField(max_length=100)
    imail_prof = models.CharField(max_length=100)
    nome_modul = models.CharField(max_length=100)
    type_shm = models.CharField(max_length=6, choices=COLOR_CHOICES, default='green')
    title_tp = models.CharField(max_length=100)
    description_tp = models.CharField(max_length=500)
    fiche_tp = models.FileField(upload_to='uploads/')
    img = models.ImageField(upload_to='info_tp_img/')

    def __str__(self):

        return self.title_tp

src/mimar/hemidi/views.py
from django.shortcuts import render
from .models import  info_tp
# Create your views here.
from .forme import  post_form
import serial
from time import sleep
##$
from django.views.generic.base import TemplateView
from django.contrib.auth import login, authenticate
from django.shortcuts import render
# Create your views here.
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forme import  NameForm
from django.contrib.auth import login, authenticate , user_logged_in
from django.shortcuts import render, redirect
from .forme import  SignUpForm
from django.contrib.auth import logout
from django.contrib.auth.models import User
#from articles.models import Article
"""
You are trying to use the reverse resolution of urls in Django.

In your html file correct form action url to the following and method should be POST:

<form action={% url 'process' %}  method="POST">
In case you are trying to pass parameters along then use this:

<form action={% url 'process' request.user.id 4 %}  method="POST">

"""



class HomePageView(TemplateView):

    template_name = "hp.html"

    def get_context_data(self, request,**kwargs):

        # Redirect to a success page.
        if request.user.is_active :

            print('yess')
        else :
            print('nnnn')

        context = super().get_context_data(**kwargs)
        context['all_post'] = info_tp.objects.all()
        return context






def all_post(request):

    if request.user.is_active:
        all_postes = info_tp.objects.all()
        contax = {
            'all_post' : all_postes ,

        }
        #print('hhhh')
        return render(request , 'hp.html',contax)
    else :
        return  redirect('/home_page/')




def un_post(request,id):
    #import pdb
    #pdb.set_trace()


    all_postes_ = info_tp.objects.get(id=id)
    #print(all_postes_.type_shm)
    contax = {
        'all_post': all_postes_,

    }


    return render(request, 'un_p.html', contax)





def pag_post(request,id):
    #import pdb
    #pdb.set_trace()
    #print(id)


    all_postes_ = info_tp.objects.get(id=id)


    contax = {
        'all_post': all_postes_,

    }

    return render(request, 'post_info.html', contax)

"""def form_p(request) :
    if  request.method == 'POST' :
        form = post_form(request.post)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
    else :
        form = post_form()

    contax = {'form' : form ,}

    return  render(request , 'form.html' , contax)
"""
def arduino_g(n) :
    ser = serial.Serial('/dev/ttyUSB0', baudrate=9600,
                        bytesize=serial.EIGHTBITS,
                        parity=serial.PARITY_NONE,
                        stopbits=serial.STOPBITS_ONE,
                        timeout=1,
                        xonxoff=0,
                        rtscts=0
                        )
    counter = 0

    n = bytes(str(n),'utf-8')

    ser.write(n)

    if counter == 255:
        with ser:  # the reset part is actually optional but the sleep is nice to have either way.
            ser.setDTR(False)
            sleep(1)
            ser.flushInput()
            ser.setDTR(True)

def get_name(request):
    logout_view(request)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            username = request.POST['your_name']
            password = request.POST['your_pass']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Redirect to a success page.

                print('yess')
                m = HomePageView
                return  redirect('/home/')

            else:
                # Return an 'invalid login' error message.
                print('non')
                #pass

            #print(password)
            return HttpResponseRedirect('/home_page/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'login.html', {'form': form})


def signup(request):
    logout_view(request)
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/home/login/')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})
def logout_view(request):
    logout(request)
    # Redirect to a success page.
    redirect('/home_page/')

src/mimar/hemidi/templates/all_p.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hemidi_benameur</title>
</head>
<body>
{% for i in all_post %}
<div class = 'post_all' >
    <h1> {{ i.title_tp }}  </h1>
    <p> {{ i.description_tp }}  </p>
    <h1> {{ i.id }}</h1>
    <button>  ok   </button>

</div>
{% endfor %}


</body>
</html>

src/mimar/hemidi/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/mimar/hemidi/templates/hp.html
{% load static %}


<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!--<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> -->
<link rel="stylesheet" href="{% static 'stl1.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}
</style>
<body>

<!-- Sidebar (hidden by default) -->
<nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:40%;min-width:300px" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()"
  class="w3-bar-item w3-button">Close Menu</a>
  <a href="#food" onclick="w3_close()" class="w3-bar-item w3-button">Food</a>
  <a href="login" onclick="w3_close()" class="w3-bar-item w3-button">logout</a>
</nav>

<!-- Top menu -->
<div class="w3-top">
  <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
    <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
    <div class="w3-right w3-padding-16">Mail</div>
    <div class="w3-center w3-padding-16">My Food</div>
  </div>
</div>

<!-- !PAGE CONTENT! -->
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">

  <!-- First Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center" id="food">
      {% for  i  in all_post  %}
    <a href="{%  url 'hemidi:un_post' i.id %} " ><div  class="w3-quarter">
      <img src="{{ i.img.url }}" alt="Sandwich" style="width:100%">
      <h1 >  {{ i.nome_modul}}</h1>
      <h3>{{ i.title_tp  }}</h3>
      <p>{{ i.description_tp}}</p>
    </div> <a/>
      {% endfor  %}
  </div>

  <!-- Second Photo Grid-
  <div class="w3-row-padding w3-padding-16 w3-center">
    <div class="w3-quarter">
      <img src="/w3images/popsicle.jpg" alt="Popsicle" style="width:100%">
      <h3>All I Need Is a Popsicle</h3>
      <p>Lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/salmon.jpg" alt="Salmon" style="width:100%">
      <h3>Salmon For Your Skin</h3>
      <p>Once again, some random text to lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/sandwich.jpg" alt="Sandwich" style="width:100%">
      <h3>The Perfect Sandwich, A Real Classic</h3>
      <p>Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/croissant.jpg" alt="Croissant" style="width:100%">
      <h3>Le French</h3>
      <p>Lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
  </div> -->

  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a href="#" class="w3-bar-item w3-button w3-hover-black">«</a>
      <a href="#" class="w3-bar-item w3-black w3-button">1</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">2</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">3</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">4</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">»</a>
    </div>
  </div>

  <hr id="about">

  <!-- About Section -->
  <div class="w3-container w3-padding-32 w3-center">
    <h3>About Me, The Food Man</h3><br>
    <img src="/w3images/chef.jpg" alt="Me" class="w3-image" style="display:block;margin:auto" width="800" height="533">
    <div class="w3-padding-32">
      <h4><b>I am Who I Am!</b></h4>
      <h6><i>With Passion For Real, Good Food</i></h6>
      <p>Just me, myself and I, exploring the universe of unknownment. I have a heart of love and an interest of lorem ipsum and mauris neque quam blog. I want to share my world with you. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
    </div>
  </div>
  <hr>

  <!-- Footer -->
  <footer class="w3-row-padding w3-padding-32">
    <div class="w3-third">
      <h3>FOOTER</h3>
      <p>Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
      <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
    </div>

    <div class="w3-third">
      <h3>BLOG POSTS</h3>
      <ul class="w3-ul w3-hoverable">
        <li class="w3-padding-16">
          <img src="/w3images/workshop.jpg" class="w3-left w3-margin-right" style="width:50px">
          <span class="w3-large">Lorem</span><br>
          <span>Sed mattis nunc</span>
        </li>
        <li class="w3-padding-16">
          <img src="/w3images/gondol.jpg" class="w3-left w3-margin-right" style="width:50px">
          <span class="w3-large">Ipsum</span><br>
          <span>Praes tinci sed</span>
        </li>
      </ul>
    </div>

    <div class="w3-third w3-serif">
      <h3>POPULAR TAGS</h3>
      <p>
        <span class="w3-tag w3-black w3-margin-bottom">Travel</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">New York</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Dinner</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Salmon</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">France</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Drinks</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Ideas</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Flavors</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Cuisine</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Chicken</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Dressing</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fried</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fish</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Duck</span>
      </p>
    </div>
  </footer>

<!-- End page content -->
</div>

<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}
</script>

</body>
</html>

src/mimar/hemidi/templates/login.html
<h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>

src/mimar/hemidi/templates/post_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/mimar/hemidi/templates/signup.html
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>